# .pre-commit-config.yaml
repos:
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.85.2 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: zs_cc_cf_template_.*\.(json|yml|yaml)$
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    -   id: gitlint
  - repo: https://github.com/Yelp/detect-secrets
    rev:  v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--exclude-lines', 'secretsmanager:'] #don't flag the secretsmanager permissions as sensitive